apiVersion: v1
kind: ServiceAccount
metadata:
  name: testing8
  namespace: team1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing8
  namespace: team1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing8
      version: v1
  template:
    metadata:
      labels:
        app: testing8
        version: v1
    spec:
      serviceAccountName: testing8
      containers:
      - image: docker.io/asayahtest/testing8
        imagePullPolicy: IfNotPresent
        name: testing8
        ports:
        - containerPort: 8080