---
apiVersion: v1
kind: Service
metadata:
  name: testing8
  namespace: team1
  labels:
    app: testing8
    service: testing8
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: testing8